# Generated by Django 4.2.27 on 2026-02-03 07:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total weight')),
                ('used_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='used weight')),
                ('unit', models.CharField(default='kg', help_text='Weight unit (e.g., kg, lbs)', max_length=10, verbose_name='unit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'trip capacity',
                'verbose_name_plural': 'trip capacities',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('mode', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('train', 'Train'), ('plane', 'Plane'), ('ship', 'Ship'), ('other', 'Other')], default='car', max_length=20, verbose_name='mode of transport')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('from_location', models.CharField(db_column='from_location', max_length=255, verbose_name='from location')),
                ('to_location', models.CharField(db_column='to_location', max_length=255, verbose_name='to location')),
                ('departure_date', models.DateField(verbose_name='departure date')),
                ('departure_time', models.TimeField(verbose_name='departure time')),
                ('transport_details', models.TextField(blank=True, help_text='Additional details about the transport', verbose_name='transport details')),
                ('category', models.CharField(blank=True, choices=[('documents', 'Documents'), ('electronics', 'Electronics'), ('clothing', 'Clothing'), ('food', 'Food'), ('medicine', 'Medicine'), ('fragile', 'Fragile'), ('other', 'Other')], help_text='Preferred category of items to carry', max_length=50, verbose_name='preferred category')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or requirements', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('capacity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='trips.tripcapacity', verbose_name='capacity')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='traveler')),
            ],
            options={
                'verbose_name': 'trip',
                'verbose_name_plural': 'trips',
                'ordering': ['-departure_date', '-departure_time'],
            },
        ),
    ]
