# Generated by Django 4.2.27 on 2026-02-07 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='booking_reference',
            field=models.CharField(blank=True, help_text='Booking or ticket reference number', max_length=100, null=True, verbose_name='booking reference'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_from', to='core.location', verbose_name='from location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='mode',
            field=models.CharField(choices=[('trip', 'Trip'), ('train', 'Train'), ('ship', 'Ship'), ('bus', 'Bus')], default='trip', max_length=20, verbose_name='mode of transport'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], default='valid', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_to', to='core.location', verbose_name='to location'),
        ),
    ]
