# Generated by Django 4.2.27 on 2026-02-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_airline'),
        ('trips', '0002_trip_booking_reference_alter_trip_from_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='airline',
            field=models.ForeignKey(blank=True, help_text='Airline for air travel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='core.airline', verbose_name='airline'),
        ),
        migrations.AddField(
            model_name='trip',
            name='meeting_points',
            field=models.JSONField(blank=True, default=list, help_text='List of meeting point locations', verbose_name='meeting points'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_availability_end_date',
            field=models.DateField(blank=True, help_text='End date for pickup availability', null=True, verbose_name='pickup availability end date'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_availability_start_date',
            field=models.DateField(blank=True, help_text='Start date for pickup availability', null=True, verbose_name='pickup availability start date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
    ]
