# Generated by Django 4.2.27 on 2026-03-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_airline_trip_meeting_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('traveling', 'Traveling'), ('completed', 'Completed')], default='valid', max_length=20, verbose_name='status'),
        ),
    ]
