# Generated by Django 4.2.27 on 2026-03-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether the trip has been approved by admin.', verbose_name='is approved'),
        ),
    ]
