# Generated by Django 4.2.27 on 2026-03-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='ticket_image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_tickets/', verbose_name='ticket image'),
        ),
    ]
