# Generated by Django 4.2.27 on 2026-03-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='ticket_image',
            field=models.CharField(blank=True, help_text='S3 URL of the ticket image', max_length=500, null=True, verbose_name='ticket image URL'),
        ),
    ]
