# Generated by Django 4.2.27 on 2026-03-05 22:45

from django.db import migrations, models
import django.db.models.deletion


def clear_old_category_values(apps, schema_editor):
    """Clear old string category values using raw SQL before column type change."""
    schema_editor.execute("UPDATE trips_trip SET category = NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipment_is_approved'),
        ('trips', '0007_alter_ticket_image_to_charfield'),
    ]

    operations = [
        # Step 1: Make the existing CharField nullable so we can clear values
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
        # Step 2: Clear all old string values
        migrations.RunPython(clear_old_category_values, migrations.RunPython.noop),
        # Step 3: Convert to ForeignKey
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Preferred category of items to carry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='shipments.category', verbose_name='preferred category'),
        ),
    ]
