# Generated by Django 4.2.27 on 2026-02-12 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('iata_code', models.CharField(help_text='2-letter airline code (e.g., AA, BA, EK)', max_length=3, unique=True, verbose_name='IATA code')),
                ('country', models.CharField(help_text='Headquarters country', max_length=100, verbose_name='country')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='logo URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'airline',
                'verbose_name_plural': 'airlines',
                'ordering': ['name'],
            },
        ),
    ]
