# Generated by Django 4.2.27 on 2026-04-19 15:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_airline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('alpha_2', models.CharField(help_text='ISO 3166-1 alpha-2 code (e.g., US, GB, AE)', max_length=2, unique=True, verbose_name='alpha-2 code')),
                ('alpha_3', models.CharField(help_text='ISO 3166-1 alpha-3 code (e.g., USA, GBR, ARE)', max_length=3, unique=True, verbose_name='alpha-3 code')),
                ('numeric_code', models.CharField(blank=True, help_text='ISO 3166-1 numeric code', max_length=3, verbose_name='numeric code')),
                ('region', models.CharField(blank=True, help_text='Continent/region (e.g., Europe, Asia, Americas)', max_length=100, verbose_name='region')),
                ('sub_region', models.CharField(blank=True, help_text='Sub-region (e.g., Northern Europe, Southern Asia)', max_length=100, verbose_name='sub-region')),
                ('flag_emoji', models.CharField(blank=True, max_length=10, verbose_name='flag emoji')),
                ('has_airports', models.BooleanField(default=False, help_text='Whether this country has at least one airport in the database', verbose_name='has airports')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='longitude'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'ordering': ['country__name', 'name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='airline',
            name='country_ref',
            field=models.ForeignKey(blank=True, help_text='Structured reference to Country model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airlines', to='core.country', verbose_name='country reference'),
        ),
        migrations.AddField(
            model_name='location',
            name='city_ref',
            field=models.ForeignKey(blank=True, help_text='Structured reference to City model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airports', to='core.city', verbose_name='city reference'),
        ),
    ]
