# Generated by Django 4.2.27 on 2026-03-07 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='disabled at')),
                ('receiver', models.ForeignKey(help_text='The user who received the original request', on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_as_receiver', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='requests.request', verbose_name='request')),
                ('sender', models.ForeignKey(help_text='The user who sent the original request', on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_as_sender', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'chatroom',
                'verbose_name_plural': 'chatrooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='text', max_length=10, verbose_name='message type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('file', models.FileField(blank=True, null=True, upload_to='chatrooms/files/%Y/%m/', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatrooms.chatroom', verbose_name='chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['chatroom', 'created_at'], name='msg_chatroom_time_idx'), models.Index(fields=['is_deleted'], name='msg_deleted_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['sender', 'receiver'], name='chatroom_participants_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['is_active'], name='chatroom_active_idx'),
        ),
    ]
