# Generated by Django 4.2.27 on 2026-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='file'),
        ),
    ]
