# Generated by Django 4.2.27 on 2026-03-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0002_change_file_to_urlfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_seen',
            field=models.BooleanField(default=False, help_text='Whether the message has been seen by the other participant.', verbose_name='is seen'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chatroom', 'is_seen'], name='msg_chatroom_seen_idx'),
        ),
    ]
