# Generated by Django 4.2.27 on 2026-03-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0003_add_is_seen_to_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='original_filename',
            field=models.CharField(blank=True, help_text='The original filename of the uploaded file.', max_length=500, null=True, verbose_name='original filename'),
        ),
    ]
