# Generated by Django 4.2.27 on 2026-02-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='id_card_number',
            field=models.CharField(blank=True, help_text='Number written on the ID card', max_length=50, null=True, verbose_name='ID card number'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='id_card_back_url',
            field=models.URLField(blank=True, help_text='URL of uploaded back side of ID card', max_length=500, null=True, verbose_name='ID card back image URL'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='id_card_front_url',
            field=models.URLField(blank=True, help_text='URL of uploaded front side of ID card', max_length=500, null=True, verbose_name='ID card front image URL'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number submitted for verification', max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='selfie_with_id_url',
            field=models.URLField(blank=True, help_text='URL of uploaded selfie holding ID card', max_length=500, null=True, verbose_name='selfie with ID image URL'),
        ),
    ]
