# Generated by Django 4.2.27 on 2026-03-29 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission amount collected from the payer.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='commission amount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_charged',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount charged to payer (reward + payer commission).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total charged'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Original reward amount (what the receiver sees).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
