# Generated by Django 4.2.27 on 2026-03-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_user_verified_and_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ziiname',
            field=models.CharField(blank=True, help_text="User's Ziina username for payment transfers.", max_length=255, verbose_name='Ziina username'),
        ),
    ]
