# Generated by Django 4.2.27 on 2026-03-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_ziiname'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='ziina_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ziina username'),
        ),
    ]
