# Generated by Django 4.2.27 on 2026-03-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersettings_ziina_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ziiname',
        ),
    ]
