# Generated by Django 4.2.27 on 2026-02-04 23:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.DecimalField(decimal_places=2, help_text='Price offered for the delivery', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='offered price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='status')),
                ('message', models.TextField(blank=True, help_text='Optional message with the request', null=True, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('receiver', models.ForeignKey(help_text='User who receives the request', on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('sender', models.ForeignKey(help_text='User who initiated the request', on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='shipments.shipment', verbose_name='shipment')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='trips.trip', verbose_name='trip')),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounterOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Counter offer price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('message', models.TextField(blank=True, help_text='Optional message with the counter offer', null=True, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('receiver', models.ForeignKey(help_text='User who receives this counter offer', on_delete=django.db.models.deletion.CASCADE, related_name='received_counter_offers', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_offers', to='requests.request', verbose_name='request')),
                ('sender', models.ForeignKey(help_text='User who made this counter offer', on_delete=django.db.models.deletion.CASCADE, related_name='sent_counter_offers', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'counter offer',
                'verbose_name_plural': 'counter offers',
                'ordering': ['created_at'],
            },
        ),
    ]
