# Generated by Django 4.2.27 on 2026-04-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='S3 URL of the delivery confirmation QR code', max_length=500, null=True, verbose_name='QR code URL'),
        ),
        migrations.AddField(
            model_name='request',
            name='qr_token',
            field=models.CharField(blank=True, help_text='Secret token embedded in QR code for delivery verification', max_length=64, null=True, verbose_name='QR token'),
        ),
    ]
