# Generated by Django 4.2.27 on 2026-02-07 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_from', to='core.location', verbose_name='from location'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_to', to='core.location', verbose_name='to location'),
        ),
    ]
