# Generated by Django 4.2.27 on 2026-02-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_category_model_and_category_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentitem',
            name='category_name',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
