# Generated by Django 4.2.27 on 2026-03-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_remove_shipmentitem_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether the shipment has been approved by admin.', verbose_name='is approved'),
        ),
    ]
