# Generated by Django 4.2.27 on 2026-03-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipment_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=30, verbose_name='status'),
        ),
    ]
