# Generated by Django 4.2.27 on 2026-03-02 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed')], max_length=20, verbose_name='action')),
                ('entity_type', models.CharField(choices=[('trip', 'Trip'), ('shipment', 'Shipment'), ('request', 'Request'), ('user', 'User'), ('verification', 'Verification')], max_length=20, verbose_name='entity type')),
                ('entity_id', models.UUIDField(help_text='ID of the affected entity.', verbose_name='entity ID')),
                ('description', models.TextField(help_text='Human-readable description of the activity.', verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data: old/new status, changed fields, etc.', verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action. Null for system events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
            ],
            options={
                'verbose_name': 'activity log',
                'verbose_name_plural': 'activity logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='admin_panel_created_9d55af_idx'), models.Index(fields=['entity_type', '-created_at'], name='admin_panel_entity__7b08f3_idx'), models.Index(fields=['action', '-created_at'], name='admin_panel_action_99e27f_idx')],
            },
        ),
    ]
