# Generated by Django 4.2.27 on 2026-03-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(choices=[('trip', 'Trip'), ('shipment', 'Shipment'), ('request', 'Request'), ('user', 'User'), ('verification', 'Verification'), ('chatroom', 'Chatroom')], max_length=20, verbose_name='entity type'),
        ),
    ]
