# Generated by Django 4.2.27 on 2026-04-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_chatroom_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='description_ar',
            field=models.TextField(blank=True, default='', help_text='Arabic translation of the activity description.', verbose_name='description (Arabic)'),
        ),
    ]
