# Generated by Django 4.2.27 on 2026-02-04 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('category', models.CharField(choices=[('request', 'Request'), ('counter_offer', 'Counter Offer'), ('shipment', 'Shipment'), ('trip', 'Trip'), ('system', 'System')], default='system', max_length=20, verbose_name='category')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('request_id', models.UUIDField(blank=True, help_text='ID of related request, if any', null=True, verbose_name='request ID')),
                ('shipment_id', models.UUIDField(blank=True, help_text='ID of related shipment, if any', null=True, verbose_name='shipment ID')),
                ('trip_id', models.UUIDField(blank=True, help_text='ID of related trip, if any', null=True, verbose_name='trip ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
