# Generated by Django 4.2.27 on 2026-02-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('platform', 'Platform'), ('traveler', 'Traveler'), ('shopping', 'Shopping'), ('shipment_request', 'Shipment Request'), ('shipment_sent', 'Shipment Sent'), ('other', 'Other')], default='other', max_length=20, verbose_name='category'),
        ),
    ]
